-- Run this in your Supabase SQL editor (https://supabase.com/dashboard/project/PROJECT_REF/sql/new)
-- This creates tables for the Aether backend.

CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT DEFAULT '',
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.milestones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  due_date TEXT,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  day_of_week TEXT NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  milestone_id BIGINT REFERENCES public.milestones(id) ON DELETE SET NULL,
  alarm_enabled BOOLEAN DEFAULT TRUE,
  actual_minutes_spent INTEGER DEFAULT 0,
  completed BOOLEAN DEFAULT FALSE,
  date TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.reflections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL UNIQUE,
  adherence_score INTEGER NOT NULL,
  focus_score INTEGER NOT NULL,
  energy_score INTEGER NOT NULL,
  notes_success TEXT DEFAULT '',
  notes_struggles TEXT DEFAULT '',
  notes_improvements TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
